---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.8.12
  deprecations_as_errors: true
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
  sudo: true

platforms:
  - name: fedora-30
    driver:
      box: bento/fedora-30

suites:
  - name: default
    run_list:
      - recipe[rpm-fusion::default]
    verifier:
      inspec_tests:
        - test/integration/default
